apiVersion: v1            
kind: deployment                                                    # Create a deployment
metadata:
  name: nginx-deployment                                            # Name of the deployment
spec:                                                               # Desired state of the deployment
  replicas: 3
  selector:                                                        # Manage pod whose label is app: nginx
    matchLabels:
      app: nginx
  template:                     # Pod blueprint
    metadata:
      labels:
        app: nginx
    spec:                         # Pod specification
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# Deployment manages pods via Replicaset and provides scaling, auto-healing, and rolling updates.
# The above YAML file defines a Kubernetes deployment for an Nginx web server with 3 replicas.

#commands to create deployment
# kubectl apply -f deployment.yml (to create deployment)
# kubectl get deployments          (to check deployment status)
# kubectl get pods                  (to check pods status)
# kubectl exec -it <pod_name> -- /bin/bash   (to access the pod's shell)